pip3 install PyYAML
pip3 install shapely
pip3 install pyyaml
pip3 install scipy
pip3 install easydict
pip3 install tensorboardX
pip3 install gaft
pip3 install pytorch=0.3.1
pip3 install torchvision
pip3 install opencv-python==3.1.0.5
pip3 install numpy==1.12.1
pip3 install hyperopt
pip3 install ray==0.6.3
pip3 install requests
